# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246300e1470b3ca0f7edada2a52e1f8a9162effcf58a0190665dd9914b5884e3c122f4f8db8749a8ea09a090b1760765fd80c7ca4cc12e91d829805f9dff085d

test:
  secret_key_base: daa220ac11d0f22d5eeb0b88a32050d2cdc75011a0ac4584ebf56598c369d9503893104f42cc86120e67d05509c9468940d53068192adb421cd8aa3d83970957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
