# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53515dc045bdb4f5781beda7d8c55938f0c258bd981cf4b09ae701ba87a2f3a771c57dde2cb7062ce86d87e00f76b670d521b774e2edee89ffb17a1646c93bd

test:
  secret_key_base: f46e37008573f0b6da1dcce348ad4c8d12b7c9b7224fe904f62f1324a979a084d75aa616c6a3dc0d617fd13a38766062eef9b8948adc8b7b231089cca17959db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
