# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 724c2b2f726c5c160a04695c669b213b3c3dda63b2d96541ed125a21d48a0516978a5ada8be6359fcc45fef16c4759288cc7e60e81718f2e4a265a145975219a

test:
  secret_key_base: 0b531228c85023d853fff932f6d38e50d96f401d8cf0d753f9f56c5ace3fb168343327780de059de534e345fc841edcac5f7ff9a99180f449d1034ffb1d14f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
